defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.0.4
  image-name:
    type: string
    default: infra-monitor

jobs:
  buildandtest:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - run: echo "This is docker image ID << pipeline.parameters.image-tag >>"
      - checkout
      - setup_remote_docker
      - run:
          name: build and tag image from dockerfile, run sanity tests
          command: |
            echo "CIRCLE_BRANCH=${CIRCLE_BRANCH}"
            TAG_LATEST=nilbydefault
            echo "TAG_LATEST=${TAG_LATEST}"
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              TAG_LATEST=<< pipeline.parameters.image-tag >>
              echo "master building with tag: << pipeline.parameters.image-tag >>"
            else
              if [ ${CIRCLE_BRANCH} == "sandbox" ]; then
                TAG_LATEST=latest
                echo "Sandbox building with tag: latest"
              fi
            fi
            echo $TAG_LATEST
            docker build -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST .
            docker image inspect ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST
            if [ $TAG_LATEST = nilbydefault ]; then
              echo "This is neither Sandbox not Master, so will not push image"
              circleci-agent step halt
            else
              docker login -u ${dockerhubusername} -p ${dockerhubpassword}
              docker push ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST
            fi            
        
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - buildandtest:
          context: contextprestage