defaults: &workdirAndImage
  working_directory: ~/taskmanagementsystem
  docker:
    - image: docker:17.05.0-ce-git
version: 2
jobs:
  checkoutcode:
    <<: *workdirAndImage
    steps: 
      - checkout:
          path: ~/taskmanagementsystem
      - persist_to_workspace:
          root: /tmp/dir
          paths:
            - images
  build:
    <<: *workdirAndImage 
    steps:
      - run: docker build -f ~/taskmanagementsystem/dockerfile .

  test:
    <<: *workdirAndImage
    steps:
      - run: docker image ls
  push_docker_image:
    <<: *workdirAndImage
    steps:
      - run: docker login -u dockerhubusername -p dockerhubpassword
      - run: docker push IMAGENAME/TAG
      #- run: |
      #    TAG=0.1.$CIRCLE_BUILD_NUM
      #    docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
      #    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #    docker push CircleCI-Public/circleci-demo-docker:$TAG 

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - push_docker_image:
          requires:
            - test
          filters:
            branches:
              only: master
