version: 2
jobs:
  build-and-test:
    working_directory: ~/taskmanagementsystem
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        command: cd nestjs-task-managment && npm install
    - run:
        command: cd nestjs-task-managment && nest --version
workflows:
  build-and-test:
    jobs:
    - build-and-test
  version: 2