  
version: 2.1
jobs:
  build:
    working_directory: ~/nestjs-task-management
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      