defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.0.3
  image-name:
    type: string
    default: infra-monitor

jobs:
  buildandtest:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - run: echo "This is docker image ID << pipeline.parameters.image-tag >>"
      - checkout
      - setup_remote_docker
      - run:
          name: build and tag image from dockerfile, run sanity tests
          command: |
            BUILD_DATE=`date -u +%Y-%m-%d`
            docker build -f ./dockerfile -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>.$BUILD_DATE .
            docker image inspect ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>.$BUILD_DATE
            docker run --publish 3000:3000 --detach --name testcontainer ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>.$BUILD_DATE
            docker rm --force testcontainer
      - run:
          name: push to dockerhub
          command: |
            echo "$ {CIRCLE_BRANCH}"
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; 
            then
              docker login -u ${dockerhubusername} -p ${dockerhubpassword}
              docker push ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>.$BUILD_DATE 
            fi
            
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - buildandtest:
          context: contextprestage