defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.0.8
  image-name:
    type: string
    default: infra-monitor

setup-image-name-tag: &setup-image-name-tag
  docker:
    - image: docker:17.05.0-ce-git
  name: Setup tagname for << pipeline.parameters.image-tag >>
  command: |
    echo "CIRCLE_BRANCH=${CIRCLE_BRANCH}"
    TAG_LATEST=nilbydefault
    echo "TAG_LATEST=${TAG_LATEST}"
    if [ ${CIRCLE_BRANCH} == "master" ]; then
      TAG_LATEST=<< pipeline.parameters.image-tag >>
      echo "master building with tag: << pipeline.parameters.image-tag >>"
    else
      if [ ${CIRCLE_BRANCH} == "sandbox" ]; then
        TAG_LATEST=latest
        echo "Sandbox building with tag: latest"
      fi
    fi
    echo "TAG_LATEST=${TAG_LATEST}"
    echo "export TAG_LATEST=${TAG_LATEST}" >> ${BASH_ENV}
    source ${BASH_ENV}
    echo "TAG_LATEST=${TAG_LATEST}"
jobs:
  buildandtest:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - run: *setup-image-name-tag
      - run: echo "This is docker image ID << pipeline.parameters.image-tag >>"
      - run: source ${BASH_ENV}
      - run: echo "TAG_LATEST={$TAG_LATEST}"

workflows:
  version: 2
  build_test_push:
    jobs:
      - buildandtest:
          context: contextprestage
