defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.0.0
  image-name:
    type: string
    default: infra-monitor

setup-image-name-tag: &setup-image-name-tag
  name: Setup TAG environment variable for << pipeline.parameters.image-name >> 
  command: |
    if [ ${CIRCLE_BRANCH} == "master" ]; then
      DOCKER_TAG=<< pipeline.parameters.image-tag >>
    else
      if [ ${CIRCLE_BRANCH} == "sandbox" ]; then
        DOCKER_TAG=latest
      fi
    fi
    echo "export DOCKER_TAG=${DOCKER_TAG}" >> ~/.bashrc
    source ~/.bashrc
    echo "INFO: Tag created for << pipeline.parameters.image-name >>:${DOCKER_TAG}, Branch: ${CIRCLE_BRANCH}"
jobs:
  buildandpush:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: *setup-image-name-tag
      - run:
          name: tag, build and push image << pipeline.parameters.image-name >>
          command: |
            source ~/.bashrc
            docker build -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:$DOCKER_TAG .
            docker image inspect ${dockerhubusername}/<< pipeline.parameters.image-name >>:$DOCKER_TAG
            docker run --rm ${dockerhubusername}/<< pipeline.parameters.image-name >>:$DOCKER_TAG ls -alR
            docker login -u ${dockerhubusername} -p ${dockerhubpassword}
            docker push ${dockerhubusername}/<< pipeline.parameters.image-name >>:$DOCKER_TAG
            echo "SUCCESS: Push to dockerhub for << pipeline.parameters.image-name >>:${DOCKER_TAG}, Branch: ${CIRCLE_BRANCH}"


workflows:
  version: 2
  build_push:
    jobs:
      - buildandpush:
          filters:
            branches:
              only:
                - sandbox
                - master
          context: contextprestage
