  
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/nestjs-task-management
    steps:
      - checkout
      - run:
          name: update-npm
          command: cd ~/nestjs-task-management && 'ls -l'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      