defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.1.${CIRCLE_WORKFLOW_ID}
  image-name:
    type: string
    default: infra-monitor

jobs:
  build:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - run: echo "This is docker image ID << pipeline.parameters.image-tag >>"
      - checkout
      - setup_remote_docker
      - run:
          name: build and store image from dockerfile to docker-imagestore
          command: |
            docker build -f ./dockerfile -t ${dockerusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> .
            mkdir -p docker-imagestore
            docker save -o docker-imagestore/built-image.tar ${dockerusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>
      - persist_to_workspace:
          root: /root/workspace/repo
          paths:
            - ./docker-imagestore/
  test:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - run: echo "This is docker image ID << pipeline.parameters.image-tag >>"
      - attach_workspace:
          at: /root/workspace/repo
      - setup_remote_docker
      - run:
          name: Start Test container and run some tests
          command: |
            docker load < docker-imagestore/built-image.tar
            docker image ls
            docker run --publish 3000:3000 --detach --name testcontainer ${dockerusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>
            docker rm --force testcontainer

  push_docker_image:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: /root/workspace/repo
      - setup_remote_docker
      - run:
          name: Get the image and push to dockerhub
          command: |
            docker load < docker-imagestore/built-image.tar
            docker image ls
            docker login -u ${dockerusername} -p ${dockerpassword}
            docker push ${dockerusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - push_docker_image:
          requires:
            - build
          filters:
            branches:
              only: master
