defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.0.0
  image-name:
    type: string
    default: infra-monitor

setup-image-name-tag: &setup-image-name-tag
  name: Setup TAG environment variable for << pipeline.parameters.image-name >> 
  command: |
    TAG_LATEST=${CIRCLE_BRANCH}
    if [ ${CIRCLE_BRANCH} == "master" ]; then
      TAG_LATEST=<< pipeline.parameters.image-tag >>
    else
      if [ ${CIRCLE_BRANCH} == "sandbox" ]; then
        TAG_LATEST=latest
      fi
    fi
    echo "export APP_TAG=${APP_TAG}" >> ~/.bashrc
    echo "export TAG_LATEST=${TAG_LATEST}" >> ~/.bashrc
    source ~/.bashrc
    echo "Info: Tag created for << pipeline.parameters.image-name >>:${TAG_LATEST}, Branch: ${CIRCLE_BRANCH} branch"
jobs:
  buildandtest:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: *setup-image-name-tag
      - run:
          name: build and tag image from dockerfile
          command: |
            source ~/.bashrc
            docker build -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST .
            docker image inspect ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST
            if [ $TAG_LATEST = ${CIRCLE_BRANCH} ]; then
              echo "Neither Sandbox nor Master, image must not be pushed"
            else
              docker login -u ${dockerhubusername} -p ${dockerhubpassword}
              docker push ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST
              echo "Success: Push to dockerhub for << pipeline.parameters.image-name >>:${TAG_LATEST}, Branch: ${CIRCLE_BRANCH} branch"
            fi

workflows:
  version: 2
  build_test_push:
    jobs:
      - buildandtest:
          context: contextprestage
