version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: cd nestjs-task-management && sudo npm install -g npm@5
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: cd nestjs-task-management && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: run test
          command: cd nestjs-task-management && npm i && npm test --passWithNoTests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build