defaults: &workdirAndImage
  working_directory: ~/workspace
  docker:
    - image: docker:17.05.0-ce-git
version: 2
jobs:
  checkoutcode:
    <<: *workdirAndImage
    steps: 
      - checkout:
          path: ~/workspace
      - persist_to_workspace:
          root: /workspace
          paths:
            - repo/
  build:
    <<: *workdirAndImage 
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: ls -al
      - setup_remote_docker
      - run: docker login -u navdeepsinghghotra -p Infy@123
      - run: docker version #build -f ~/workspace/dockerfile .
      - run:
          name: use the dockerfile
          command: docker build -f ./dockerfile -t my_app:$CIRCLE_BRANCH .
      - run: docker image ls
      - run: mkdir -p docker-cache
      - run: docker save -o docker-cache/built-image.tar my_app:$CIRCLE_BRANCH
      - save_cache:
          key: docker_cache_key
          paths:
            - docker-cache
  test:
    <<: *workdirAndImage
    working_directory: ~/workspace/repo
    steps:
      - restore_cache:
          keys:
            - docker_cache
      - attach_workspace:
          at: ./
      - run: ls -al
      - setup_remote_docker    
      - run: 
          name: Deploy
          command: |
            docker load < docker-cache/built-image.tar
            docker image ls
            rm -r < docker-cache/
      #- setup_remote_docker
      #- run: docker image ls
      
  push_docker_image:
    <<: *workdirAndImage
    steps:
      - run: docker login -u dockerhubusername -p dockerhubpassword
      - run: docker push IMAGENAME/TAG
      #- run: |
      #    TAG=0.1.$CIRCLE_BUILD_NUM
      #    docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
      #    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #    docker push CircleCI-Public/circleci-demo-docker:$TAG 

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - push_docker_image:
          requires:
            - test
          filters:
            branches:
              only: master
