defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.1.${CIRCLE_WORKFLOW_ID}
  image-name:
    type: string
    default: infra-monitor

jobs:
  buildandtest:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - run: echo "This is docker image ID << pipeline.parameters.image-tag >>"
      - run: echo $envname
      - checkout
      - setup_remote_docker
      - run:
          name: build and tag image from dockerfile, store to folder docker-imagestore
          command: |
            docker build -f ./dockerfile -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> .
            docker run --publish 3000:3000 --detach --name testcontainer ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>
            docker rm --force testcontainer

  buildandpushimage:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - run: echo $envname
      - setup_remote_docker
      - run:
          name: build and tag image from dockerfile, store to folder docker-imagestore
          command: |
            docker build -f ./dockerfile -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> .
            mkdir -p docker-imagestore
            docker save -o docker-imagestore/<< pipeline.parameters.image-name >>-image.tar ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>
      - run:    
          name: push to dockerhub
          command: |
            docker load < docker-imagestore/<< pipeline.parameters.image-name >>-image.tar
            docker image ls
            docker login -u ${dockerhubusername} -p ${dockerhubpassword}
            docker push ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - buildandtest:
          context: contextprestage
          filters:
            branches:
              ignore: master
      - buildandpushimage:
          context: contextlive
          filters:
            branches:
              only: master