defaults: &workdirAndImage
  working_directory: ~/workspace
  docker:
    - image: docker:17.05.0-ce-git
version: 2
jobs:
  checkoutcode:
    <<: *workdirAndImage
    steps: 
      - checkout:
          path: ~/workspace
      - persist_to_workspace:
          root: /workspace
          paths:
            - repo/
  build:
    <<: *workdirAndImage 
    steps:
      - attach_workspace:
          at: ~/workspace/repo/
      - run: |
          cd ~/workspace/repo/  
          ls -al
      - run: |
          sudo service docker start
          docker login -u navdeepsinghghotra -p Infy@123
      #- run: docker version #build -f ~/workspace/dockerfile .

  test:
    <<: *workdirAndImage
    steps:
      - run: docker image ls
  push_docker_image:
    <<: *workdirAndImage
    steps:
      - run: docker login -u dockerhubusername -p dockerhubpassword
      - run: docker push IMAGENAME/TAG
      #- run: |
      #    TAG=0.1.$CIRCLE_BUILD_NUM
      #    docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
      #    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #    docker push CircleCI-Public/circleci-demo-docker:$TAG 

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - push_docker_image:
          requires:
            - test
          filters:
            branches:
              only: master
