defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.0.8
  image-name:
    type: string
    default: infra-monitor

setup-image-name-tag: &setup-image-name-tag
  docker:
    - image: docker:17.05.0-ce-git
  name: Setup APP_TAG environment variable
  command: |
    echo "CIRCLE_BRANCH=${CIRCLE_BRANCH}"
    TAG_LATEST=
    echo "TAG_LATEST=${TAG_LATEST}"
    if [ ${CIRCLE_BRANCH} == "master" ]; then
      TAG_LATEST=<< pipeline.parameters.image-tag >>
      echo "master building with tag: << pipeline.parameters.image-tag >>"
    else
      if [ ${CIRCLE_BRANCH} == "sandbox" ]; then
        TAG_LATEST=latest
        echo "Sandbox building with tag: latest"
      fi
    fi
    echo "export APP_TAG=${APP_TAG}" >> ~/.bashrc
    echo "export TAG_LATEST=${TAG_LATEST}" >> ~/.bashrc
    source ~/.bashrc
    echo "TAG_LATEST=${TAG_LATEST}"
jobs:
  buildandtest:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - run: echo "This is docker image ID << pipeline.parameters.image-tag >>"
      - checkout
      - setup_remote_docker
      - run: *setup-image-name-tag
      - run:
          name: build and tag image from dockerfile
          command: |
            source ~/.bashrc
            echo $TAG_LATEST
            TAG_LATEST="$TAG_LATEST:$CIRCLE_BRANCH}"
            echo $TAG_LATEST
            docker build -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST .
            docker image inspect ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST
            if [$TAG_LATEST = ${CIRCLE_BRANCH} ]; then
              echo "This is neither Sandbox not Master, so will not push image"
            else
              docker login -u ${dockerhubusername} -p ${dockerhubpassword}
              docker push ${dockerhubusername}/<< pipeline.parameters.image-name >>:$TAG_LATEST
              echo "push to dockerhub for << pipeline.parameters.image-name >> from ${CIRCLE_BRANCH} with tag $TAG_LATEST completed successfully"
            fi

workflows:
  version: 2
  build_test_push:
    jobs:
      - buildandtest:
          context: contextprestage
