defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git

version: 2.1
parameters:
  image-tag:
    type: string
    default: 0.1.${date}
  image-name:
    type: string
    default: infra-monitor

jobs:
  buildandtest:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - run: echo "This is docker image ID << pipeline.parameters.image-tag >>"
      - run: 
          name: get build date
          command: |
            BUILD_DATE=`date -u +”%Y-%m-%d”`
            echo $BUILD_DATE
      - run: DATENOW=`date` 
      - checkout
      - setup_remote_docker
      - run:
          name: build and tag image from dockerfile, run sanity tests
          command: |
            docker build -f ./dockerfile -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>.$BUILD_DATE .
            docker run --publish 3000:3000 --detach --name testcontainer ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>.$BUILD_DATE
            docker rm --force testcontainer

  buildandpushimage:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - run: echo $envname
      - setup_remote_docker
      - run:
          name: build and tag image from dockerfile, push to dockerhub
          command: |
            docker build -f ./dockerfile -t ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> .
            docker image ls
            docker login -u ${dockerhubusername} -p ${dockerhubpassword}
            docker push ${dockerhubusername}/<< pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - buildandtest:
          context: contextprestage
          filters:
            branches:
              ignore: master
      - buildandpushimage:
          context: contextlive
          filters:
            branches:
              only: master