defaults: &Image
  docker:
    - image: docker:17.05.0-ce-git
version: 2
jobs:
  build:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - setup_remote_docker
      - run:
          name: build and store image from dockerfile to docker-imagestore
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -f ./dockerfile -t navdeepsinghghotra/my_app:$TAG .
            mkdir -p docker-imagestore
            docker save -o docker-imagestore/built-image.tar navdeepsinghghotra/my_app:$TAG
      - persist_to_workspace:
          root: /root/workspace/repo
          paths:
            - ./docker-imagestore/
  test:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: /root/workspace/repo
      - setup_remote_docker
      - run:
          name: Start Test container and run some tests
          command: |
            docker load < docker-imagestore/built-image.tar
            docker run --publish 3000:3000 --detach --name testcontainer navdeepsinghghotra/my_app:$TAG
            docker rm --force testcontainer

  push_docker_image:
    <<: *Image
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: /root/workspace/repo
      - setup_remote_docker
      - run:
          name: Get the image and push to dockerhub
          command: |
            docker load < docker-imagestore/built-image.tar
            docker image ls
            docker login -u navdeepsinghghotra -p Infy@123
            docker push navdeepsinghghotra/my_app:$TAG

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - push_docker_image:
          filters:
            branches:
              only: master
