defaults: &workdirAndImage
  working_directory: ~/workspace
  docker:
    - image: docker:17.05.0-ce-git
version: 2
jobs:
  build:
    <<: *workdirAndImage
    working_directory: ~/workspace/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - setup_remote_docker
      - run:
          name: build image from dockerfile
          command: docker build -f ./dockerfile -t navdeepsinghghotra/my_app:$CIRCLE_BRANCH .
      - run:
          name: store docker image
          command: |
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar navdeepsinghghotra/my_app:$CIRCLE_BRANCH
      - persist_to_workspace:
          root: /root/workspace/repo
          paths:
            - ./docker-cache/
  test:
    <<: *workdirAndImage
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: /root/workspace/repo
      - setup_remote_docker
      - run:
          name: Deploy
          command: |
            docker load < docker-cache/built-image.tar
            docker run --publish 3000:3000 --detach --name testcontainer navdeepsinghghotra/my_app:$CIRCLE_BRANCH
            docker rm --force testcontainer

  push_docker_image:
    <<: *workdirAndImage
    working_directory: ~/workspace/repo
    steps:
      - attach_workspace:
          at: /root/workspace/repo
      - setup_remote_docker
      - run:
          name: Get the image and push to dockerhub
          command: |
            docker load < docker-cache/built-image.tar
            docker image ls
            docker login -u navdeepsinghghotra -p Infy@123
            docker push navdeepsinghghotra/my_app:$CIRCLE_BRANCH

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - push_docker_image:
          requires:
            - build
          filters:
            branches:
              only: master
